const individuals = [
  {
    ardaId: 39226565,
    ggId: '1562283',
    name: 'Nilton Segura',
    comparableName: 'nilton segura',
    username: 'niltonsegura',
    professionalHeadline: 'Full Stack Software Developer',
    imageUrl: 'https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v1692485522/origin/starrgate/users/profile_8ad2bc932f581ad389efd786124da08a8e5ba0fd.jpg',
    completion: 0.7895,
    grammar: 0,
    weight: 1309.3236,
    verified: true,
    connections: [],
    totalStrength: 0,
    pageRank: 0.9093117269829135,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 8381027,
    ggId: '11018',
    name: 'Nilton Ruiz',
    comparableName: 'nilton ruiz',
    username: 'niltonruiz',
    professionalHeadline: 'Environmental consultant',
    imageUrl: 'https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v0/origin/starrgate/users/profile_dfb4cdf7b995a88791de5cd575cee20ec21c6fa5.jpg',
    completion: 0.9375,
    grammar: 0.68667,
    weight: 0,
    verified: true,
    connections: [],
    totalStrength: 0,
    pageRank: 0.3104066827575715,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 8885480,
    ggId: '737305',
    name: 'Nilton Cesar Arcos Chito',
    comparableName: 'nilton cesar arcos chito',
    username: 'ceesitar93',
    professionalHeadline: 'Desarrollador',
    imageUrl: null,
    completion: 0.7059,
    grammar: 0.57241,
    weight: 753.7263,
    verified: true,
    connections: [],
    totalStrength: 0,
    pageRank: 0.27264698298149875,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 36581767,
    ggId: '1512540',
    name: 'Nilton Anthony Reyna Colqui',
    comparableName: 'nilton anthony reyna colqui',
    username: 'anthonynilton3',
    professionalHeadline: 'Asistente Profesional',
    imageUrl: null,
    completion: 0.5,
    grammar: 0,
    weight: 0,
    verified: false,
    connections: [],
    totalStrength: 0,
    pageRank: 0.23336122164360623,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 8215519,
    ggId: '1111995',
    name: 'Nilton Yuvan Sanchez Echeverri',
    comparableName: 'nilton yuvan sanchez echeverri',
    username: 'niltonyuvansanchezecheverri',
    professionalHeadline: 'Diseñador Gráfico y Desarrollador Web',
    imageUrl: null,
    completion: 0.2941,
    grammar: 0.6,
    weight: 0,
    verified: false,
    connections: [],
    totalStrength: 0,
    pageRank: 0.15768989878424944,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 8272163,
    ggId: '528354',
    name: 'Nilton Duran',
    comparableName: 'nilton duran',
    username: 'abyjesus9',
    professionalHeadline: 'Debt Settlement Cunselor and English Speaking Tutor',
    imageUrl: null,
    completion: 0.2941,
    grammar: 0.86667,
    weight: 0,
    verified: false,
    connections: [],
    totalStrength: 0,
    pageRank: 0.15721893168550055,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 22764594,
    ggId: '295818bea9e343709002fe39ee1395f6',
    name: 'Nilton Alexander Rodríguez Hernández',
    comparableName: 'nilton alexander rodriguez hernandez',
    username: '16234c05-2239-4e58-9ae1-1606a59a04d5',
    professionalHeadline: null,
    imageUrl: null,
    completion: 0,
    grammar: 1,
    weight: 0,
    verified: false,
    connections: [],
    totalStrength: 0,
    pageRank: 0.15432104064654226,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 7815368,
    ggId: '1250304',
    name: 'Nilton César Salazar Bonilla',
    comparableName: 'nilton cesar salazar bonilla',
    username: 'niltonsalazar',
    professionalHeadline: 'Gestor de Proyectos / Servicios',
    imageUrl: 'https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v1650327965/origin/starrgate/users/profile_4b09739d20a810ceba90121028a419ac54388d66.jpg',
    completion: 0.6111,
    grammar: 0.52009,
    weight: 0,
    verified: false,
    connections: [],
    totalStrength: 0,
    pageRank: 0.1525100554355252,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 9034325,
    ggId: '652256',
    name: 'Cesar Nilton Vincenty Funes',
    comparableName: 'cesar nilton vincenty funes',
    username: 'cesarnvf',
    professionalHeadline: 'Ingeniero de Sistemas',
    imageUrl: null,
    completion: 0.1765,
    grammar: 1,
    weight: 0,
    verified: false,
    connections: [],
    totalStrength: 0,
    pageRank: 0.1519834230998361,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
  {
    ardaId: 9136300,
    ggId: '210181',
    name: 'Jair Nilton Bolaño De La Hoz',
    comparableName: 'jair nilton bolano de la hoz',
    username: 'jairbolano',
    professionalHeadline: 'Licenciado en Contaduría Pública',
    imageUrl: 'https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v0/origin/starrgate/users/profile_218816973fd9ba6b9e149a74ceead65850dee7a5.jpg',
    completion: 0.7647,
    grammar: 0.44966,
    weight: 0,
    verified: true,
    connections: [],
    totalStrength: 0,
    pageRank: 0.15000000000000002,
    organizationId: null,
    organizationNumericId: null,
    publicId: null,
    status: null,
    creators: [],
    relationDegree: 1,
    contact: false,
  },
];

export default individuals;
